apiVersion: batch/v1
kind: Job
metadata:
 name: job1
 namespace: team-a
spec:
 template:
   spec:
     containers:
       - name: job1
         image: gcr.io/run-ai-demo/quickstart
         resources:
           limits:
             nvidia.com/gpu: 1
     restartPolicy: Never  
