---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: team-a-user
  namespace: team-a

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: team-a-user-full-access
  namespace: team-a
rules:
  - apiGroups: ["", "extensions", "apps", "batch"]
    resources: ["*"]
    verbs: ["*"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: team-a-user-view
  namespace: team-a
subjects:
  - kind: ServiceAccount
    name: team-a-user
    namespace: team-a
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: team-a-user-full-access